# Section 4: NumPy

In [1]:
import numpy as np

## Arrays

In [2]:
my_list = [1, 2, 3]

In [3]:
type(my_list)

list

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_array = np.array(my_list)

In [6]:
type(my_array)

numpy.ndarray

In [7]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((4, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [14]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
np.random.rand(5, 6)

array([[0.01117568, 0.53750534, 0.58749166, 0.93003801, 0.52826127,
        0.80737882],
       [0.17697594, 0.87540861, 0.05653638, 0.451127  , 0.4374561 ,
        0.39502188],
       [0.92431436, 0.73939694, 0.01879764, 0.66607166, 0.85760771,
        0.7120119 ],
       [0.70686926, 0.47233579, 0.10483962, 0.87739469, 0.21993956,
        0.34540507],
       [0.57465883, 0.87706469, 0.80322446, 0.765271  , 0.66013875,
        0.06420443]])

In [16]:
np.random.randn(10)

array([-0.72088929,  0.80995825, -0.85457897, -0.11262515, -1.06191664,
        0.62868206,  1.94952966,  1.21512832,  0.32992022, -0.40607529])

In [17]:
np.random.randn(2, 3)

array([[-2.04181614, -1.34492483, -1.54100298],
       [ 0.78705439, -0.56307462,  0.3320387 ]])

In [18]:
np.random.randint(0, 101, (4, 5))

array([[71, 36, 20, 24,  1],
       [55, 70, 42, 83, 85],
       [64, 70, 11, 70,  6],
       [29, 26, 11, 68, 72]])

In [19]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [20]:
arr = np.arange(0, 25)

In [21]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
rand_arr = np.random.randint(0, 101, 10)

In [23]:
rand_arr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [24]:
rand_arr.max()

99

In [25]:
rand_arr.min()

2

In [26]:
rand_arr.argmax()

5

In [27]:
rand_arr.argmin()

7

In [28]:
rand_arr.dtype

dtype('int64')

In [29]:
arr.shape

(25,)

In [30]:
arr = arr.reshape(5, 5)

In [31]:
arr.shape

(5, 5)

In [32]:
arr = arr.reshape(25, 1)

In [33]:
arr.shape

(25, 1)

## Indexing and Selection

In [34]:
arr = np.arange(0, 11)

In [35]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[8]

8

In [37]:
arr[1:5]

array([1, 2, 3, 4])

In [38]:
arr[:5]

array([0, 1, 2, 3, 4])

In [39]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[:5] = 100

In [42]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [43]:
arr = np.arange(0, 11)

In [44]:
slice_of_arr = arr[0:5]

In [45]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
slice_of_arr[:] = 99

In [48]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [49]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [50]:
arr_copy = arr.copy()

In [51]:
arr_copy[:] = 100

In [52]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [53]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [54]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [55]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [56]:
arr_2d.shape

(3, 3)

In [57]:
arr_2d[0, 2]

15

In [58]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [59]:
arr = np.arange(1, 11)    

In [60]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [62]:
bool_arr = arr > 4

In [63]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [64]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [65]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## Operations

In [66]:
arr = np.arange(0, 10)

In [67]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [70]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [71]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [72]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [73]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [74]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr.sum()

45

In [77]:
arr.mean()

4.5

In [78]:
arr.var()

8.25

In [79]:
arr.std()

2.8722813232690143

In [80]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [81]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [82]:
arr_2d.sum()

300

In [83]:
arr_2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [84]:
arr_2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

## Exercises

In [85]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [86]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [87]:
np.full(10, 5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [88]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [89]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [90]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [92]:
np.random.rand(1)

array([0.96990985])

In [93]:
np.random.randn(25)

array([-0.46947439,  0.54256004, -0.46341769, -0.46572975,  0.24196227,
       -1.91328024, -1.72491783, -0.56228753, -1.01283112,  0.31424733,
       -0.90802408, -1.4123037 ,  1.46564877, -0.2257763 ,  0.0675282 ,
       -1.42474819, -0.54438272,  0.11092259, -1.15099358,  0.37569802,
       -0.60063869, -0.29169375, -0.60170661,  1.85227818, -0.01349722])

In [94]:
np.linspace(0.01, 1, 100).reshape(10, 10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [95]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [96]:
mat = np.arange(1, 26).reshape(5, 5)

In [97]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [98]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [99]:
mat[3, 4]

20

In [100]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [101]:
mat[4, :]

array([21, 22, 23, 24, 25])

In [102]:
mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [103]:
mat.sum()

325

In [104]:
mat.std()

7.211102550927978

In [105]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [106]:
np.random.seed(42)
np.random.rand()

0.3745401188473625